name = "Murshid Starter"
license = "MIT"
licenselink = "https://github.com/murshidazher/murshid/blob/master/LICENSE"
description = "Theme description"
homepage = "https://github.com/murshidazher/murshid"
tags = ["blog", "company"]
features = ["some", "awesome", "features"]
min_version = "0.69.0"

[author]
    name = "Your name"
    homepage = "Your website"

# If porting an existing theme
[original]
    author = "Murshid Azher"
    homepage = "https://murshidazher.com"
    repo = "Link to source code of original theme"
